name: deploy

on:
  workflow_run:
    workflows: ["tests", "linter"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: ${{ secrets.DO_PORT }}
          script: |
            cd /var/www/secretlab

            git pull origin main

            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            npm ci --production
            npm run build

            php artisan down
            php artisan optimize:clear
            php artisan migrate --force

            php artisan optimize
            php artisan up
